spring:
  data:
    mongodb:
      database: pets
      host: localhost
      port: 27017

stripe:
  keys:
    public: pk_test_QEAzhKXVN6ScM2W2mH44g9Ip00FymwtHyN
    secret: sk_test_RAMJbRSQ0OcKa8Qrrg837vHp00RA2X3zf0

amazonProperties:
  endpointUrl: https://s3.eu-west-1.amazonaws.com
  accessKey: AKIAZSNGYNFUDOI6D44B
  secretKey: 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
  bucketName: backend-pet-images